### ISSUE TITLE
Command "mobculler" and smart-cleaner doesn't work

### ISSUE THREAD

**Issue by WaxenSs** [alvindimas05/LagAssist#7]
Hey! first of all, thanks for this fork, it's a tool I use a lot on my server, I'm glad it's available in 1.21 thanks to you! I don't know why but the command `lagassist mobculler` doesn't work... The mobs I put in the list are not deleted. I'm afraid the smart-cleaner won't work either...
The command doesn't work whether I'm in the terminal or even with my player account with the perm `lagassist.use`

```
# Smart cleaner removes mobs based on the below configuration...
#
# TIP: This will not remove named mobs, even if they are in the list.
# This follows the vanilla rule - don't despawn named entities, which
# players are already accustomed to.
smart-cleaner:
  # Do you want the system to be in whitelist or blacklist mode?
  # TIP: Whitelist - All except these get deleted ; Blacklist is the opposite
  whitelist: false
  # The plugin will begin to cull mobs if the TPS drops below the set value.
  # EG: If TPS is under 16, LagAssist will begin to cull mobs that are named below.
  # TIP: Set to 0.0 to disable it.
  maxtps-cull: 13.0
  # Automatically disable mob spawning if TPS is under this value.
  # EG: If TPS is under 14, LagAssist will disable mob spawning.
  maxtps-disablespawn: 10.0
  # List of the mobs that will get removed (or kept) by the smart-cleaner - (depending on whitelist or blacklist)
  # Mob names: htttps://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
  mobs:
  - "DROWNED"
  - "HOGLIN"
  - "PHANTOM"
  - "SLIME"
  - "ZOMBIE"
  - "CREEPER"
  - "SKELETON"
  - "WITHER_SKELETON"
  - "SQUID"
  - "SPIDER"
  - "SILVERFISH"
  - "PIG_ZOMBIE"
  - "ILLUSIONER"
  - "GHAST"
  - "HUSK"
  - "EVOKER"
  - "ENDERMAN"
  - "ENDERMITE"
  - "GUARDIAN"
  - "CAVE_SPIDER"
  - "BAT"
  - "BLAZE"
# Others
  - "ARROW"
```
